//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/WorkStation/compilador/GameSharp.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GameSharpParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGameSharpVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] GameSharpParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] GameSharpParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.objectDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectDecl([NotNull] GameSharpParser.ObjectDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.objectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectBody([NotNull] GameSharpParser.ObjectBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.propertyDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDecl([NotNull] GameSharpParser.PropertyDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.actionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionDecl([NotNull] GameSharpParser.ActionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] GameSharpParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] GameSharpParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] GameSharpParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.comp_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_expr([NotNull] GameSharpParser.Comp_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] GameSharpParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.objectProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectProperty([NotNull] GameSharpParser.ObjectPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp([NotNull] GameSharpParser.OpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_op([NotNull] GameSharpParser.Comp_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] GameSharpParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] GameSharpParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] GameSharpParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] GameSharpParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadStatement([NotNull] GameSharpParser.ReadStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameSharpParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] GameSharpParser.FunctionCallContext context);
}
